apiVersion: v1
kind: ServiceAccount

metadata:
  name: cluster-autoscaler
  namespace: kube-system

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::163567208906:role/cc-adtest-cluster-autoscaler