apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopkart-deployment
spec:
  replicas: 3

  selector:
      matchLabels:
        app : backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: shopkart-backend
        image: shopkart-backend:v1
        ports:
        - containerPort: 8000