apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopkart-deployment
spec:
  replicas: 3

  selector:
      matchLabels:
        app : backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: shopkart-backend
        image: 163567208906.dkr.ecr.us-east-1.amazonaws.com/cc-adtest-b:v1
        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres@postgres-svc:5432/shopkart"
        ports:
        - containerPort: 8000