apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopkart-deployment
spec:
  replicas: 3

  selector:
      matchLabels:
        app : backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: shopkart-backend
        image: 163567208906.dkr.ecr.us-east-1.amazonaws.com/cc-adtest-b:v3
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: DATABASE_URL
        ports:
        - containerPort: 8000

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"