apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres
  
  ports:
    - port: 5432  # Port where the backend will connect (can be eg: 9000 also)
      targetPort: 5432 # Port of the postgres pod

  type: ClusterIP
