apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: gp3

provisioner: ebs.csi.aws.com

volumeBindingMode: WaitForFirstConsumer

parameters:
  type: gp3
  tagSpecification_1: "Usage=cookiecutter"
  tagSpecification_2: "Group=DST"
  tagSpecification_3: "Owner=aditi.jaiswal@numerator.com"

reclaimPolicy: Delete
allowVolumeExpansion: true